### PR TITLE
Optionally show last modified on single template

### PR DESCRIPTION
**Pull request by vxnick**
if `params.showLastmod: true` and `.Lastmod`'s timestamp is greater than `.Date`, show the last modified date next to the publish date.

Happy to change the wording of "published" and "updated".

### CODE REVIEW

**Comment by tomfran** [comment]
Hi, can you please include a screenshot of the result?

**Comment by vxnick** [comment]
Sure, before:

Screenshot 2024-09-30 at 09 05 40

With `lastmod` frontmatter set:

Screenshot 2024-09-30 at 09 05 33

**Comment by tomfran** [comment]
Do you know if one could specify custom strings in the `singleDateFormat`? I am asking because "published" is not included in the code.

If this is the case, we could add a `singleDateUpdatedFormat` or something similar, to allow someone to customize it freely, without hardcoding the "updated" string. 

So a user, to get the result you posted, could set them to: 

```toml
singleDateFormat = 'Published 2 January 2006'
singleDateUpdatedFormat = 'Updated 2 January 2006'
```

What do you think?

**Comment by vxnick** [comment]
I've tested this but it doesn't appear that arbitrary strings are supported - Hugo just prints out `Updated :date_long`.

Would splitting the dates into another partial be an acceptable solution?

**Comment by tomfran** [comment]
Thank you for testing it :)

Maybe we can leave the current date if last mod is not present, otherwise write:

"Published ... • Updated ..."

I feel this would be a general-enough solution, do you agree or have other ideas?

**Comment by vxnick** [comment]
Keeping the current date and only prefixing it where last mod exists sounds good to me. I'll update the PR soon

**Comment by tomfran** [comment]
Sorry but I had to force push some changes to remote large files from the history. If you want to include this, or future changes, please update your fork. Sorry for the inconvenience

**Pull request closed without merging**
