### PR TITLE
Added a configurable option to open a new tab when clicking on the menu and support for Umami along with relevant configurable options.

### PR DESCRIPTION
**Pull request by jkfujr**
```
[[params.menu]]
name = "posts"
url = "/posts"
newTab = true
```

`newTab = true` is an optional setting and can be omitted.

### CODE REVIEW

**Review by jkfujr — COMMENTED** [review]
Umami configurable options:
```
# umami
[params.umami]
enable = true
websiteId = "unique-website-id"
jsLocation = "http://example.org/umami.js"
```

**Comment by tomfran** [comment]
The new tab config looks good, but about umami, when is that script tag executed? Shouldn't we include it like it's done for comments? 

Something like: 

```
{{ if .Site.Params.umami.enable }}
...
{{ end }}
```

**Comment by jkfujr** [comment]
> The new tab config looks good, but about umami, when is that script tag executed? Shouldn't we include it like it's done for comments?
> 
> Something like:
> 
> ```
> {{ if .Site.Params.umami.enable }}
> ...
> {{ end }}
> ```

Alright, you are right, let's use a consistent coding style.

**Review by jkfujr — COMMENTED** [review]
This is correct now

**Comment by tomfran** [comment]
Great, could you please squash everything in a single commit while resolving conflicts? Then I can merge

**Comment by jkfujr** [comment]
> Great, could you please squash everything in a single commit while resolving conflicts? Then I can merge

OK

**Pull request merged**
