### PR TITLE
feat: Content License and Copyright holder as Footer

### PR DESCRIPTION
**Pull request by arunmathaisk**
```
[params]
showFooterLicense = true
licenseType = "CC BY-SA 4.0"
copyrightYear = "2024"
copyrightHolder = "Arun Mathai"

```

Screenshot 2024-09-14 at 12 37 16 AM

Solves #25

### CODE REVIEW

**Comment by tomfran** [comment]
Thank you for the pull request! I like the idea of your footer, but I think a more generic implementation would be better. 

Something like: 

```
[params]
showFooter = true|false // default to true
footerContent = "Custom MD footer content."
```

So basically the same we are doing for home intro content.

This would allow users to have a custom footer (something I am seeing a lot in the forks) and decide to hide it completely if needed. 

Also, I don't like the idea of having two footer files, one with some logic would be more than enough.

**Comment by arunmathaisk** [comment]
Makes sense.

**Comment by tomfran** [comment]
If you want to make those changes feel free to update the PR 👍

**Comment by arunmathaisk** [comment]
[params]
showFooter = true
footerContent = """
Hahahahah
"""

If showFooter is set to true and footerContent is not set, your default attribution is shown.
If showFooter is false, no footer is shown, not even the author attribution.

**Comment by tomfran** [comment]
This looks good, but the `showFooter` param must default to true for this change to be backward compatible.
So something like: if the param is not set or it's true, then show the footer.

**Comment by arunmathaisk** [comment]
Lol. forgot about backward compatibility.  Glad to see you care about it :) 
Here take a look
https://github.com/tomfran/typo/pull/24/commits/ef9948b2aee58dc785bfbb844f8e18d219b913fa

**Pull request merged**
